### ISSUE TITLE
ECFP implementation example

### ISSUE THREAD

**Issue by tsnguyen05** [bayer-science-for-a-better-life/neuraldecipher#2]
Dear Tuan Le,

Your group's new implementation method is a game-changer on updating chemistry prediction. I have read your article to understand how the code works. I wonder whether a source code of implementing ECFP is also published through this repository by chance?

**Comment by tuanle618** [comment]
Hey @tsnguyen05 , thanks for your interest. In our work, we utilized the ECFP algorithm provided by the `rdkit`. See https://github.com/bayer-science-for-a-better-life/neuraldecipher/blob/master/source/get_ecfp.py#L25 .
 The original ECFP algorithm is implemented in C++, for source code, see https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/Fingerprints/MorganFingerprints.cpp#L72-L305

**Comment by tsnguyen05** [comment]
Hello @tuanle618,

Thank you so much for providing 2 ECFP algorithms for this work. Since I can understand Python language, your provided website from your group's link helps me a lot.
